application: minyattra
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

handlers:
######################### REST ENDPOINTS #########################
- url: /api/users/github/pull
  script: handlers.rest.users.app

######################### STATIC ENDPOINTS #########################

- url: /assets/css
  static_dir: assets/css
  secure: never

- url: /assets/js
  static_dir: assets/js
  secure: never

- url: /assets/img
  static_dir: assets/img
  secure: never

- url: /assets/fonts
  static_dir: assets/fonts
  secure: never

######################### WEB ENDPOINTS #########################
- url: /users/.*
  script: handlers.web.auth.app

- url: /member/.*
  script: handlers.web.add_member.app

- url: /add_company
  script: handlers.web.add_member.app

- url: /.*
  script: handlers.web.index.app

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'