application: minyattra
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

handlers:

######################### REST ENDPOINTS #########################


######################### STATIC ENDPOINTS #########################


######################### WEB ENDPOINTS #########################

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
